INSERT INTO ABSTRACT_USER (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('emp1@gmail.com', 'Andriy', '$2a$10$bWG7aOnbX1hy.hdVMJQcSOmM/1dH9N1gOxPx8760B0ReklT/tVjXu', 'MANAGER');
INSERT INTO ABSTRACT_USER (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('emp2@gmail.com', 'Maria', '$2a$10$bWG7aOnbX1hy.hdVMJQcSOmM/1dH9N1gOxPx8760B0ReklT/tVjXu', 'MANAGER');
INSERT INTO ABSTRACT_USER (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('emp3@gmail.com', 'Mykola', '$2a$10$bWG7aOnbX1hy.hdVMJQcSOmM/1dH9N1gOxPx8760B0ReklT/tVjXu', 'MANAGER');


INSERT INTO EMPLOYEE (ID, DEPARTMENT, STATUS)
VALUES (1, 'IT', 'ACTIVE');
INSERT INTO EMPLOYEE (ID, DEPARTMENT, STATUS)
VALUES (2, 'IT', 'ACTIVE');
INSERT INTO EMPLOYEE (ID, DEPARTMENT, STATUS)
VALUES (3, 'IT', 'ACTIVE');